[package]
name = "oxide-api-prototype"
version = "0.1.0"
authors = ["David Pacheco <dap@oxidecomputer.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
futures = "0.3.1"
bytes = "0.5.4"
#log = "0.3.0"
#serde = "1.0"
#serde_derive = "1.0"
#serde_json = "1.0"
#url = {version = "1.5", optional = true}
#percent-encoding = {version = "1.0.0", optional = true}
#clap = "2.25"
