[package]
name = "oxide-api-prototype"
version = "0.1.0"
authors = ["David Pacheco <dap@oxidecomputer.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.24"
chrono = { version = "0.4", features = [ "serde" ] }
clap = "2"
futures = "0.3.1"
http = "0.2.0"
dropshot = { git = "ssh://git@github.com/oxidecomputer/dropshot" }
hyper = "0.13"
schemars = { version = "0.7", features = [ "chrono", "uuid" ] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
tokio = { version = "0.2", features = [ "full" ] }
toml = "0.5.6"
uuid = { version = "0.8", features = [ "serde", "v4" ] }

[dev-dependencies]
libc = "0.2.71"

[dependencies.slog]
version = "2.5"
features = [ "max_level_trace", "release_max_level_debug" ]

#
# It's common during development to use a local copy of dropshot in the parent
# directory.  If you want to use that, uncomment this block.
#
#[patch."ssh://git@github.com/oxidecomputer/dropshot"]
#dropshot = { path = "../dropshot" }

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
